<a href="https://colab.research.google.com/github/DahyeonS/Java_Python_Lecture/blob/main/20240103/numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 넘파이

- 파이썬에서 배열을 사용하기 위한 표준 패키지
- NumPy와 패키지의 핵심은 ndarray  배열 객체

## ndarray가 list, tuple 과 다른 점

- 모든 원소가 같은 자료형
- 크기가 고정, 크기 변경시에는 새로운 메모리에 할당 됨

## ndarray식을 계산

- 수치해석용 파이썬 패키지
- 다차원의 배열 자료구조 클래스인 ndarray 클래스를 지원
- 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용
- 넘파이의 배열 연산은 C로 구현된 내부 반복문을 사용하기 때문에 파이썬 반복문에 비해 속도가 빠름
- 벡터화 연산(vectorized operation)을 이용하여 간단한 코드로도 복잡한 선형 대수 연산을 수행
- 배열 인덱싱(array indexing)을 사용한 질의(Query) 기능을 이용하여 간단한 코드로도 복잡한 수식을 계산

```{margin}
벡터화 연산(vectorized operation)
반복문을 사용하지 않고도 배열의 모든 원소에 대해 반복연산이 가능
```

## 넘파이 패키지 import

- np라는 별명으로 import 하는 것이 관례

In [ ]:
# pip install numpy

In [3]:
import numpy as np
np.__version__

'1.23.5'

## 1차원 배열 만들기

### array() : ndarray 생성 함수


In [4]:
data = range(10)
arr = np.array(data)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
data = list(range(10))
arr = np.array(data)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### type() : 자료형 확인

In [6]:
type(arr)

numpy.ndarray

### list로 역변환 가능

In [7]:
data = list(arr)
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## 벡터화 연산(vectorized operation)

- ndarray는 반복 연산을 하나의 명령어로 처리하는 벡터화 연산(vectorized operation)을 지원

In [8]:
data = list(range(10))

- for 반복문을 사용하는 연산 : python 기본 연산

In [9]:
rs = []
for i in data:
    rs.append(2 * i)
rs

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [10]:
rs = [i*2 for i in data]
rs

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

- 벡터화 연산

In [11]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
rs = 2 * x
rs

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

* 참고 : 일반적인 리스트 객체에 정수를 곱하면 객체의 크기가 정수배 만큼으로 증가

In [13]:
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

- 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용

In [14]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [15]:
2 * a + b

array([12, 24, 36])

In [16]:
a == 2

array([False,  True, False])

In [17]:
b > 10

array([False,  True,  True])

In [18]:
(a == 2) & (b > 10)

array([False,  True, False])

## 2차원 배열

- `ndarray` 2차원 배열, 3차원 배열 등의 다차원 배열 자료 구조를 지원
- 2차원 배열은 행렬(matrix), 행렬에서는 가로줄을 행(row)과 세로줄을 열(column)로 구성 됨
- 2개의 행과 3개의 열을 가지는 2 x 3 배열이 됨

In [19]:
a = np.array([
    [0, 1, 2],
    [3, 4, 5]
])  # 2 x 3 array
a

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
# 행의 갯수
len(a)

2

In [21]:
# 열의 갯수
len(a[0])

3

## 3차원 배열

- list 3개로 3차원 배열 생성
- 3 x 2 x 3 배열은 2 x 3 행렬이 3개 있다는 의미
- 앞의 3은 2 x 3의 2차 평면의 깊이나 높이

In [22]:
a = np.array([
                [
                    [1, 2, 3],
                    [4, 5, 6]
                ],
                [
                    [10, 20, 30],
                    [40, 50, 60]
                ],
                [
                    [100, 200, 300],
                    [400, 500, 600]
                ],
            ])   # 4 x 2 x 3 array

3차원 배열의 깊이, 행, 열은 다음과 같이 구할 수 있다.

In [23]:
len(a), len(a[0]), len(a[0][0])

(3, 2, 3)

## 배열의 차원과 크기 알아내기

### ndim : 배열의 차원 확인

### shape : 배열의 크기 확인

In [24]:
print(a.ndim)
print(a.shape)

3
(3, 2, 3)


## 배열의 인덱싱

- ndarray의 인덱싱은 리스트의 인덱싱과 동일 함

In [25]:
a = np.array(range(5))

In [26]:
a[2]

2

In [27]:
a[-1]

4

## 축(axis)

### 1차원
- 행 x 방향이거나 열 y 방향 일 수 있음
- 일반 적인인 경우 행을 나타 냄

In [28]:
a = np.array(range(3))
print(a.ndim)
print(a.shape)

1
(3,)


### 2차원
- 행 x, 열 y

In [29]:
a = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
print(a.ndim)
print(a.shape)

2
(2, 3)


In [30]:
a[0][0] , a[0, 0] # 첫번째 행의 첫번째 열

(0, 0)

In [31]:
a[0][1], a[0, 1]  # 첫번째 행의 두번째 열

(1, 1)

In [32]:
a[-1][-1], a[-1, -1]  # 마지막 행의 마지막 열

(5, 5)

### 3차원
- 깊이(높이) z,
행 x, 열 y

In [33]:
a = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [10, 20, 30],
            [40, 50, 60]
        ]
])
print(a.ndim)
print(a.shape)

3
(2, 2, 3)


In [34]:
a[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
a[0][0], a[0, 0]

(array([1, 2, 3]), array([1, 2, 3]))

In [36]:
a[0][0][0], a[0, 0, 0]

(1, 1)

## 배열 슬라이싱

- ndarray의 인덱싱은 리스트의 인덱싱과 동일 함

In [37]:
a = np.array([
    range(1,6),
    range(6,11)
])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
a[0, :]  # 첫번째 행 전체

array([1, 2, 3, 4, 5])

In [ ]:
a[:, 1]  # 두번째 열 전체

array([2, 7])

In [ ]:
a[1, 1:]  # 두번째 행의 두번째 열부터 끝열까지

array([ 7,  8,  9, 10])

In [ ]:
a[:2, :2]

array([[1, 2],
       [6, 7]])

**연습**
```
arr = np.array([
    [ 1,  2,  3,  4, 5],
    [ 6,  7,  8,  9, 10],
    [ 11, 12, 13, 14, 15]
])
```

1. 값 8 인덱싱
2. 배열 [8, 13] 슬라이싱
5. 배열 [[3, 4], [8, 9]] 슬라이싱


In [ ]:
arr = np.array([
    [ 1,  2,  3,  4, 5],
    [ 6,  7,  8,  9, 10],
    [ 11, 12, 13, 14, 15]
])
print(arr[1,2])
print(arr[1:3, 2])
print(arr[:2, 2:4])

8
[ 8 13]
[[3 4]
 [8 9]]


## 팬시 인덱싱(fancy indexing)

- 인덱스 배열을 전달 한번에 여러 요소에 접근
- 불리언(Boolean) 배열 방식과 정수 배열 방식 두가지

### 불리안 배열 인덱싱 방식

In [ ]:
# 짝수만 선택
a = np.array(range(10)
b = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[b]

array([0, 2, 4, 6, 8])

#### 비교, 논리 연산으로 구현
- 논리연산자 : |, &
- 논리연산시 비교 연산은 () 필요

In [ ]:
a = np.array(range(10))
b = a % 2 == 0
print(b)
a[b]

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [ ]:
# 간단 표현
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [ ]:
# 5보다 큰 자료 선택
a[a > 5]

array([6, 7, 8, 9])

In [ ]:
# 5보다 큰 짝수 자료 선택
# a[a > 5 & a%2==0] # Error
a[(a > 5) & (a%2==0)]

array([82, 36, 32, 18, 14])

### 정수 배열 인덱싱
- 인덱스 정수 배열로 입력

In [ ]:
from random import randint
[randint(1,100) for r in range(10)]

[18, 16, 45, 2, 31, 18, 67, 79, 40, 22]

In [ ]:
import random
random.seed(42)
a = np.array([random.randint(1,100) for r in range(10)])
i = np.array([random.randint(0,9) for r in range(10)])
print(a)
print(i)
a[i]

[82 15  4 95 36 32 29 18 95 14]
[8 1 9 6 0 0 1 3 3 8]


array([95, 15, 14, 29, 82, 82, 15, 95, 95, 95])

- 배열 인덱스의 크기가 원래의 배열 크기와 달라도 상관 없음

In [ ]:
i = np.array([random.randint(0,9) for r in range(20)])
print(i,len(i))
a[i]

[3 4 1 3 1 6 4 7 5 2 5 5 3 4 1 9 2 8 3 2] 20


array([95, 36, 15, 95, 15, 29, 36, 18, 32,  4, 32, 32, 95, 36, 15, 14,  4,
       95, 95,  4])

- 배열 인덱싱은 다차원 배열의 각 차원에 대해서도 가능

In [ ]:
a = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
a[:, [True, False, False, True, False]]

array([[ 1,  4],
       [ 6,  9],
       [11, 14]])

In [ ]:
a[[2, 0, 1], :]

array([[11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

**연습**

```
arr = np.array(range(1,31)
```

1. 3의 배수 출력
2. 3의 배수이거나 5의 배수 출력
3. 3의 배수이고 5의 배수 출력

In [ ]:
arr = np.array(range(1,31))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
# 1
arr[arr % 3 ==0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
# 2
arr[(arr % 3 ==0) | (arr % 5 == 0)]

array([ 3,  5,  6,  9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30])

In [ ]:
# 3
arr[(arr % 3 ==0) & (arr % 5 == 0)]

array([15, 30])